/**
 * The frozen set of Python builtin function/type names this slice
 * attributes to the `python-stdlib` package when a bare callee matches one,
 * minting an EXTERNAL `SYMBOL` (`site:python-stdlib\`...`). Deliberately
 * small and hand-picked — see `./node-globals.ts`'s module doc for the same
 * rationale (README rule 2: no bare-name SYMBOLs for anything this table
 * doesn't attribute).
 */
export const PYTHON_BUILTIN_NAMES: ReadonlySet<string> = new Set([
  "print",
  "len",
  "range",
  "open",
  "isinstance",
  "issubclass",
  "getattr",
  "setattr",
  "hasattr",
  "type",
  "super",
  "int",
  "float",
  "str",
  "bool",
  "list",
  "dict",
  "set",
  "tuple",
  "frozenset",
  "bytes",
  "enumerate",
  "zip",
  "map",
  "filter",
  "sorted",
  "reversed",
  "sum",
  "min",
  "max",
  "abs",
  "round",
  "iter",
  "next",
  "repr",
  "format",
  "input",
  "hash",
  "id",
  "vars",
  "dir",
  "callable",
  "staticmethod",
  "classmethod",
  "property",
]);
